# Generated by Django 5.0.7 on 2024-08-07 03:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shoes",
            fields=[
                ("name", models.CharField(blank=None, max_length=100, null=None)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="shoesImage/"),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.CharField(blank=None, max_length=20, null=None)),
                ("brand", models.ManyToManyField(to="SHOES.brand")),
                ("tag", models.ManyToManyField(to="SHOES.tag")),
            ],
        ),
    ]
