# Generated by Django 5.0.7 on 2024-08-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHOES", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeShoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="shoes",
            name="size",
            field=models.ManyToManyField(to="SHOES.sizeshoe"),
        ),
    ]
