# Generated by Django 5.0.7 on 2024-08-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHOES", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
    ]
