# Generated by Django 5.0.7 on 2024-08-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHOES", "0002_sizeshoe_shoes_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoes",
            name="size",
        ),
        migrations.DeleteModel(
            name="SizeShoe",
        ),
    ]
