# Generated by Django 5.0.7 on 2024-08-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SHOES", "0005_voucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="is_active",
        ),
    ]
