# Generated by Django 5.0.7 on 2024-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SHOES", "0006_remove_voucher_expires_at_remove_voucher_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
