# Generated by Django 5.0.7 on 2024-08-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0002_alter_profile_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
