# Generated by Django 5.0.7 on 2024-08-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0003_alter_profile_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="location",
            new_name="address",
        ),
    ]
