# Generated by Django 5.0.7 on 2024-08-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0004_rename_location_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
